"""empty message

Revision ID: 350678a3ea17
Revises: 795b55fd58e5
Create Date: 2024-09-16 21:35:52.333002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350678a3ea17'
down_revision = '795b55fd58e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('featured_image')

    # ### end Alembic commands ###
