"""empty message

Revision ID: 795b55fd58e5
Revises: 
Create Date: 2024-09-12 00:39:17.383089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '795b55fd58e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=25), nullable=False))
        batch_op.create_unique_constraint(None, ['key'])
        batch_op.drop_column('value')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', mysql.VARCHAR(length=25), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('key')

    # ### end Alembic commands ###
