"""empty message

Revision ID: d9f755e4a860
Revises: 350678a3ea17
Create Date: 2024-09-19 00:08:10.874422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9f755e4a860'
down_revision = '350678a3ea17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('featured_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('featured_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    op.drop_table('subscriber')
    # ### end Alembic commands ###
